# Generated by Django 6.0.2 on 2026-07-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Enter image URL or local media path', max_length=500, null=True),
        ),
    ]
